# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6227c47f569902d68bd2707a9e97c002c97f563f96d12442b9365563f7e9a3625a79b671179e025208f469fe7e304b4d5bc962a1747afecf06fb4d21a1929fb

test:
  secret_key_base: 750fc4495b8fe8e8e04e1e14fd38d9412d65e911a402537dfb04228ebd56df6697d9a371cabe907bf154a5e1e5cbf6ba5f7e9a46d00396be2a4a102851bcc122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
